const data = [
  {
    id: 1,
    category: "camera",
    img: "https://i.postimg.cc/D0Q1BVk3/Untitled-design.png",
    title: "Canon EOS 2000D DSLR Camera (Body Only)",
    description: {
      line1: "24.1MP APS-C CMOS Sensor",
      line2: "7.5 cm (3.0-inch) TFT LCD, approx. 920 K dots",
      line3: "Display: 15.6 inch HD (1366 x 768)",
      line4: "Features: Chiclet Keyboard, Type-C",
    },
    price: "Price : 50000৳",
  },
  {
    id: 2,
    category: "camera",
    img: "camera.jpeg",
    title: "Canon Eos 4000D 18MP 2.7inch Display With 18-55mm Lens Dslr Camera",
    description: {
      line1: "18 megapixel APS-C sensor",
      line2: "Aspect Ratio 3:2",
      line3: "Lens Mount EF/EF-S",
      // line4: "Features: Backlit Keyboard, Type-C",
    },
    price: "Price : 52000৳",
  },
  {
    id: 3,
    category: "desktop",
    img: "cpu.jpg",
    title: "Intel Pentium Gold G7400 Desktop PC",
    description: {
      line1: "Intel Pentium Gold G7400 Alder Lake Processor",
      line2: "BIOSTAR H610MHP Micro ATX Motherboard",
      line3: "PNY XLR8 8GB DDR4 3200MHz Desktop Gaming RAM",
      line4: "Team MP33 256GB M.2 PCIe SSD",
    },
    price: "Price : 52000৳",
  },
  {
    id: 4,
    category: "desktop",
    img: "cpu.jpg",
    title: "AMD Ryzen 5 2400G Desktop PC",
    description: {
      line1:
        "AMD Ryzen 5 2400G Desktop Processor with Radeon RX Vega 11 Graphics",
      line2: "MSI B450M-A PRO MAX AMD AM4 Motherboard",
      line3: "Team Elite Plus Red 8GB 3200MHz DDR4 U-DIMM Desktop RAM",
      line4: "Kimtigo TP3000 256GB M.2 NVMe PCIe Gen3x4 SSD",
    },
    price: "Price : 52000৳",
  },
  {
    id: 5,
    category: "laptop",
    img: "asuslaptop.jpg",
    title: "Asus P1511CMA Intel Celeron N4020 15.6-Inch HD Laptop",
    description: {
      line1:
        "Processor: Intel Celeron N4020 (4M Cache, 1.10 GHz up to 2.80 GHz)",
      line2: "Ram: 4GB DDR4, Storage: 1TB HDD",
      line3: "Display: 15.6 inch HD (1366 x 768)",
      line4: "Features: Chiclet Keyboard, Type-C",
    },
    price: "Price : 50000৳",
  },
  {
    id: 6,
    category: "laptop",
    img: "asuslaptop.jpg",
    title: "Asus Vivobook E410MA Celeron N4020 14 HD Laptop",
    description: {
      line1:
        "Processor: Intel Celeron N4500 (4M Cache, 1.10 GHz up to 2.80 GHz)",
      line2: "Processor: A14 Bionic Chip, Storage: 64GB",
      line3: "Camera: 12MP + 12MP Rear, 12MP Front",
      line4: "Features: Face ID, eSIM Support",
    },
    price: "Price : 52000৳",
  },
  {
    id: 7,
    category: "phone",
    img: "iphone.jpeg",
    title: "iPhone 11 128GB (Singapore Unofficial)",
    description: {
      line1: `Display: 6.1" Liquid Retina HD display`,
      line2: "Processor: A13 Bionic Chip, Storage: 128GB",
      line3: "Display: 15.6 FHD (1920x1080)",
      line4: "Features: Backlit Keyboard, Type-C",
    },
    price: "Price : 52000৳",
  },
  {
    id: 8,
    category: "phone",
    img: "iphone.jpeg",
    title: "iPhone 12 64GB Blue (Singapore Unofficial)",
    description: {
      line1: `Display: 6.1" Super Retina XDR Display with OLED`,
      line2: "RAM: 4GB DDR4 RAM, Storage: 1TB 5400RPM HDD",
      line3: "Display: 15.6 FHD (1920x1080)",
      line4: "Features: Backlit Keyboard, Type-C",
    },
    price: "Price : 52000৳",
  },
  {
    id: 9,
    category: "processor",
    img: "amd.jpg",
    title: "AMD Athlon 3000G Processor with Radeon Graphics",
    description: {
      line1: "Speed: 3.5GHz",
      line2: "Cache: L2: 1MB, L3: 4MB",
      line3: "Cores-2 & Threads-4",
      line4: "Memory Speed: 2667MHz",
    },
    price: "Price : 50000৳",
  },
  {
    id: 10,
    category: "processor",
    img: "amd.jpg",
    title: "AMD Athlon 3000G Processor with Radeon Graphics",
    description: {
      line1: "Speed: 3.5GHz",
      line2: "Cache: L2: 1MB, L3: 4MB",
      line3: "Cores-2 & Threads-4",
      line4: "Memory Speed: 2667MHz",
    },
    price: "Price : 50000৳",
  },
  {
    id: 11,
    category: "projector",
    img: "projector1.jpg",
    title: "Epson EB-E01 3LCD XGA 3300 Lumens Projector",
    description: {
      line1: "Projection System: 3LCD Technology",
      line2: "LCD Panel: 55 inch with C2 Fine",
      line3: "Resolution: XGA, 1024 x 768",
      line4: "Aspect Ratio: 4:3",
    },
    price: "Price : 52000৳",
  },
  {
    id: 12,
    category: "projector",
    img: "projector1.jpg",
    title: "Epson EB-E01 3LCD XGA 3300 Lumens Projector",
    description: {
      line1: "Projection System: 3LCD Technology",
      line2: "LCD Panel: 55 inch with C2 Fine",
      line3: "Resolution: XGA, 1024 x 768",
      line4: "Aspect Ratio: 4:3",
    },
    price: "Price : 52000৳",
  },
  {
    id: 13,
    category: "smartwatch",
    img: "applewatch.jpeg",
    title: "Apple Watch Series 8 GPS 45mm Silver Aluminum Case Sport Band",
    description: {
      line1:
        "Processor: Intel Celeron N4020 (4M Cache, 1.10 GHz up to 2.80 GHz)",
      line2: "Ram: 4GB DDR4, Storage: 1TB HDD",
      line3: "Display: 15.6 inch HD (1366 x 768)",
      line4: "Features: Chiclet Keyboard, Type-C",
    },
    price: "Price : 50000৳",
  },
  {
    id: 14,
    category: "smartwatch",
    img: "applewatch.jpeg",
    title: "Apple Watch Series 8 GPS 45mm Silver Aluminum Case Sport Band",
    description: {
      line1:
        "Processor: Intel Celeron N4020 (4M Cache, 1.10 GHz up to 2.80 GHz)",
      line2: "Ram: 4GB DDR4, Storage: 1TB HDD",
      line3: "Display: 15.6 inch HD (1366 x 768)",
      line4: "Features: Chiclet Keyboard, Type-C",
    },
    price: "Price : 50000৳",
  },
  {
    id: 15,
    category: "vrbox",
    img: "vr1.jpg",
    title: "Meta Quest 2 128 GB All-in-One VR System",
    description: {
      line1: `Blazing-fast processor and highest-resolution display`,
      line2: "Two Touch Controllers",
      line3: "Storage: 128 GB",
      line4: "Compatible with PC VR",
    },
    price: "Price : 52000৳",
  },
  {
    id: 16,
    category: "vrbox",
    img: "vr1.jpg",
    title: "Meta Quest 2 128 GB All-in-One VR System",
    description: {
      line1: `Blazing-fast processor and highest-resolution display`,
      line2: "Two Touch Controllers",
      line3: "Storage: 128 GB",
      line4: "Compatible with PC VR",
    },
    price: "Price : 52000৳",
  },
  {
    id: 17,
    category: "vrbox",
    img: "vr1.jpg",
    title: "Meta Quest 2 128 GB All-in-One VR System",
    description: {
      line1: `Blazing-fast processor and highest-resolution display`,
      line2: "Two Touch Controllers",
      line3: "Storage: 128 GB",
      line4: "Compatible with PC VR",
    },
    price: "Price : 52000৳",
  },
  {
    id: 18,
    category: "vrbox",
    img: "Photo by Pixabay from Pexels: https://www.pexels.com/photo/red-dahlia-flower-60597/",
    title: "Meta Quest 2 128 GB All-in-One VR System",
    description: {
      line1: `Blazing-fast processor and highest-resolution display`,
      line2: "Two Touch Controllers",
      line3: "Storage: 128 GB",
      line4: "Compatible with PC VR",
    },
    price: "Price : 52000৳",
  },
];

export default data;
